In [50]:
import numpy as np
import pandas as pd

- El método de PCA permite por lo tanto “condensar” la información aportada por múltiples variables en solo unas pocas componentes. Esto lo convierte en un método muy útil de aplicar previa utilización de otras técnicas estadísticas tales como regresión, clustering… Aun así no hay que olvidar que sigue siendo necesario disponer del valor de las variables originales para calcular las componentes.

In [51]:
#Generamos un dataset de ayuda
X = np.random.randint(10,50,100).reshape(20,5) 

In [52]:
pd.DataFrame(X)

0   1   2   3   4
0   40  22  19  47  46
1   15  17  22  44  27
2   13  19  49  41  39
3   11  23  39  31  10
4   34  27  12  46  46
5   16  12  19  44  26
6   43  12  13  39  30
7   35  40  12  27  10
8   48  46  31  47  35
9   23  27  16  20  37
10  27  45  20  10  32
11  47  25  12  18  47
12  38  43  19  16  41
13  41  16  12  43  13
14  44  24  23  40  11
15  40  25  14  30  45
16  25  14  47  26  39
17  44  15  49  31  25
18  10  49  12  39  32
19  10  30  14  21  13

In [53]:
# Obtenemos la media de cada variable y la restamos a los registros para centralizar la infomación
X_meaned = X - np.mean(X , axis = 0)

In [54]:
X_meaned

array([[  9.8 ,  -4.55,  -3.7 ,  14.  ,  15.8 ],
       [-15.2 ,  -9.55,  -0.7 ,  11.  ,  -3.2 ],
       [-17.2 ,  -7.55,  26.3 ,   8.  ,   8.8 ],
       [-19.2 ,  -3.55,  16.3 ,  -2.  , -20.2 ],
       [  3.8 ,   0.45, -10.7 ,  13.  ,  15.8 ],
       [-14.2 , -14.55,  -3.7 ,  11.  ,  -4.2 ],
       [ 12.8 , -14.55,  -9.7 ,   6.  ,  -0.2 ],
       [  4.8 ,  13.45, -10.7 ,  -6.  , -20.2 ],
       [ 17.8 ,  19.45,   8.3 ,  14.  ,   4.8 ],
       [ -7.2 ,   0.45,  -6.7 , -13.  ,   6.8 ],
       [ -3.2 ,  18.45,  -2.7 , -23.  ,   1.8 ],
       [ 16.8 ,  -1.55, -10.7 , -15.  ,  16.8 ],
       [  7.8 ,  16.45,  -3.7 , -17.  ,  10.8 ],
       [ 10.8 , -10.55, -10.7 ,  10.  , -17.2 ],
       [ 13.8 ,  -2.55,   0.3 ,   7.  , -19.2 ],
       [  9.8 ,  -1.55,  -8.7 ,  -3.  ,  14.8 ],
       [ -5.2 , -12.55,  24.3 ,  -7.  ,   8.8 ],
       [ 13.8 , -11.55,  26.3 ,  -2.  ,  -5.2 ],
       [-20.2 ,  22.45, -10.7 ,   6.  ,   1.8 ],
       [-20.2 ,   3.45,  -8.7 , -12.  , -17.2 ]])

In [55]:
np.mean(X , axis = 0)

array([30.2 , 26.55, 22.7 , 33.  , 30.2 ])

In [56]:
# Calculaos la matriz de covarianzas
cov_mat = np.cov(X_meaned , rowvar = False)

In [57]:
pd.DataFrame(cov_mat)

0           1           2           3           4
0  187.010526   -0.536842  -27.726316    7.842105   39.221053
1   -0.536842  142.365789  -46.089474  -45.947368    9.621053
2  -27.726316  -46.089474  169.484211    9.052632   -3.305263
3    7.842105  -45.947368    9.052632  134.000000   -5.631579
4   39.221053    9.621053   -3.305263   -5.631579  167.326316

In [58]:
#Calculamos los eigenvectores y eigenvalores
eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)

In [59]:
eigen_values

array([ 82.98853203, 120.26580751, 155.6535956 , 203.03021352,
       238.24869344])

In [60]:
eigen_vectors 

array([[ 0.07993773,  0.5360087 , -0.26027111,  0.55258215, -0.57724912],
       [ 0.73049703,  0.08601925,  0.18024343, -0.51870606, -0.39677589],
       [ 0.35201182,  0.44374766,  0.52056443,  0.33325674,  0.54509477],
       [ 0.57568279, -0.51357371, -0.43202679,  0.42155925,  0.20117658],
       [-0.06827186, -0.49459621,  0.66493367,  0.36989827, -0.41442975]])

In [61]:
#Ordenamos los valores propios en orden descendente
sorted_index = np.argsort(eigen_values)[::-1]

sorted_eigenvalue = eigen_values[sorted_index]
#ordenar de manera similar los eigenvectores
sorted_eigenvectors = eigen_vectors[:,sorted_index]

In [62]:
sorted_eigenvalue 

array([238.24869344, 203.03021352, 155.6535956 , 120.26580751,
        82.98853203])

In [64]:
sorted_eigenvectors 

array([[-0.57724912,  0.55258215, -0.26027111,  0.5360087 ,  0.07993773],
       [-0.39677589, -0.51870606,  0.18024343,  0.08601925,  0.73049703],
       [ 0.54509477,  0.33325674,  0.52056443,  0.44374766,  0.35201182],
       [ 0.20117658,  0.42155925, -0.43202679, -0.51357371,  0.57568279],
       [-0.41442975,  0.36989827,  0.66493367, -0.49459621, -0.06827186]])

In [65]:
# seleccione los primeros n vectores propios, n es la dimensión deseada
# de nuestros datos reducidos finales.
 
n_components = 2 #Número de componenetes
eigenvector_subset = sorted_eigenvectors[:,0:n_components]

In [66]:
eigenvector_subset

array([[-0.57724912,  0.55258215],
       [-0.39677589, -0.51870606],
       [ 0.54509477,  0.33325674],
       [ 0.20117658,  0.42155925],
       [-0.41442975,  0.36989827]])

In [67]:
X_meaned

array([[  9.8 ,  -4.55,  -3.7 ,  14.  ,  15.8 ],
       [-15.2 ,  -9.55,  -0.7 ,  11.  ,  -3.2 ],
       [-17.2 ,  -7.55,  26.3 ,   8.  ,   8.8 ],
       [-19.2 ,  -3.55,  16.3 ,  -2.  , -20.2 ],
       [  3.8 ,   0.45, -10.7 ,  13.  ,  15.8 ],
       [-14.2 , -14.55,  -3.7 ,  11.  ,  -4.2 ],
       [ 12.8 , -14.55,  -9.7 ,   6.  ,  -0.2 ],
       [  4.8 ,  13.45, -10.7 ,  -6.  , -20.2 ],
       [ 17.8 ,  19.45,   8.3 ,  14.  ,   4.8 ],
       [ -7.2 ,   0.45,  -6.7 , -13.  ,   6.8 ],
       [ -3.2 ,  18.45,  -2.7 , -23.  ,   1.8 ],
       [ 16.8 ,  -1.55, -10.7 , -15.  ,  16.8 ],
       [  7.8 ,  16.45,  -3.7 , -17.  ,  10.8 ],
       [ 10.8 , -10.55, -10.7 ,  10.  , -17.2 ],
       [ 13.8 ,  -2.55,   0.3 ,   7.  , -19.2 ],
       [  9.8 ,  -1.55,  -8.7 ,  -3.  ,  14.8 ],
       [ -5.2 , -12.55,  24.3 ,  -7.  ,   8.8 ],
       [ 13.8 , -11.55,  26.3 ,  -2.  ,  -5.2 ],
       [-20.2 ,  22.45, -10.7 ,   6.  ,   1.8 ],
       [-20.2 ,   3.45,  -8.7 , -12.  , -17.2 ]])

In [ ]:
[  9.8 ,  -4.55,  -3.7 ,  14.  ,  15.8 ] X (1,2,3,4,5)

In [68]:
#Multiplicmos los eigenvectores por la X una vez aplicada la media
X_reduced = np.dot(eigenvector_subset.transpose(),X_meaned.transpose()).transpose()

In [69]:
#Matrix de (2,5)
pd.DataFrame(eigenvector_subset.transpose())

0         1         2         3         4
0 -0.577249 -0.396776  0.545095  0.201177 -0.414430
1  0.552582 -0.518706  0.333257  0.421559  0.369898

In [ ]:
(2,5)x(5,19)=(2,19)

In [70]:
#Matrix de (5,19)
pd.DataFrame(X_meaned.transpose())

0      1      2      3      4      5      6      7      8      9   \
0   9.80 -15.20 -17.20 -19.20   3.80 -14.20  12.80   4.80  17.80  -7.20   
1  -4.55  -9.55  -7.55  -3.55   0.45 -14.55 -14.55  13.45  19.45   0.45   
2  -3.70  -0.70  26.30  16.30 -10.70  -3.70  -9.70 -10.70   8.30  -6.70   
3  14.00  11.00   8.00  -2.00  13.00  11.00   6.00  -6.00  14.00 -13.00   
4  15.80  -3.20   8.80 -20.20  15.80  -4.20  -0.20 -20.20   4.80   6.80   

      10     11     12     13     14     15     16     17     18     19  
0  -3.20  16.80   7.80  10.80  13.80   9.80  -5.20  13.80 -20.20 -20.20  
1  18.45  -1.55  16.45 -10.55  -2.55  -1.55 -12.55 -11.55  22.45   3.45  
2  -2.70 -10.70  -3.70 -10.70   0.30  -8.70  24.30  26.30 -10.70  -8.70  
3 -23.00 -15.00 -17.00  10.00   7.00  -3.00  -7.00  -2.00   6.00 -12.00  
4   1.80  16.80  10.80 -17.20 -19.20  14.80   8.80  -5.20   1.80 -17.20

In [72]:
#Matrix de (2,19)
pd.DataFrame(np.dot(eigenvector_subset.transpose(),X_meaned.transpose()))

0          1          2         3          4          5          6   \
0  -9.60008  15.720948  25.222766  29.34591 -12.137304  15.906723  -5.613173   
1  18.28859  -0.225408   9.804049 -11.65115   9.625210   1.551036  13.843010   

          7          8         9          10         11        12        13  \
0  -6.775524 -12.640829 -5.107908 -12.318109 -24.895365 -20.94220  1.259139   
1 -17.891350  10.190502 -9.409791 -21.268229   6.412430  -8.62723  5.727731   

         14         15         16         17         18         19  
0  2.574556 -16.521453  16.171818  12.705398  -2.618615  10.263304  
1  4.897179   7.529783  12.038663  19.614751 -23.177785 -27.271990

In [73]:
pd.DataFrame(X_meaned)

0      1     2     3     4
0    9.8  -4.55  -3.7  14.0  15.8
1  -15.2  -9.55  -0.7  11.0  -3.2
2  -17.2  -7.55  26.3   8.0   8.8
3  -19.2  -3.55  16.3  -2.0 -20.2
4    3.8   0.45 -10.7  13.0  15.8
5  -14.2 -14.55  -3.7  11.0  -4.2
6   12.8 -14.55  -9.7   6.0  -0.2
7    4.8  13.45 -10.7  -6.0 -20.2
8   17.8  19.45   8.3  14.0   4.8
9   -7.2   0.45  -6.7 -13.0   6.8
10  -3.2  18.45  -2.7 -23.0   1.8
11  16.8  -1.55 -10.7 -15.0  16.8
12   7.8  16.45  -3.7 -17.0  10.8
13  10.8 -10.55 -10.7  10.0 -17.2
14  13.8  -2.55   0.3   7.0 -19.2
15   9.8  -1.55  -8.7  -3.0  14.8
16  -5.2 -12.55  24.3  -7.0   8.8
17  13.8 -11.55  26.3  -2.0  -5.2
18 -20.2  22.45 -10.7   6.0   1.8
19 -20.2   3.45  -8.7 -12.0 -17.2

In [74]:
pd.DataFrame(X_reduced)

0          1
0   -9.600080  18.288590
1   15.720948  -0.225408
2   25.222766   9.804049
3   29.345910 -11.651150
4  -12.137304   9.625210
5   15.906723   1.551036
6   -5.613173  13.843010
7   -6.775524 -17.891350
8  -12.640829  10.190502
9   -5.107908  -9.409791
10 -12.318109 -21.268229
11 -24.895365   6.412430
12 -20.942200  -8.627230
13   1.259139   5.727731
14   2.574556   4.897179
15 -16.521453   7.529783
16  16.171818  12.038663
17  12.705398  19.614751
18  -2.618615 -23.177785
19  10.263304 -27.271990

In [75]:
import numpy as np
 
def PCA(X , num_components):
     
    #1
    X_meaned = X - np.mean(X , axis = 0)
     
    #2
    cov_mat = np.cov(X_meaned , rowvar = False)
     
    #3
    eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
     
    #4
    sorted_index = np.argsort(eigen_values)[::-1]
    sorted_eigenvalue = eigen_values[sorted_index]
    sorted_eigenvectors = eigen_vectors[:,sorted_index]
     
    #5
    eigenvector_subset = sorted_eigenvectors[:,0:num_components]
     
    #6
    X_reduced = np.dot(eigenvector_subset.transpose() , X_meaned.transpose() ).transpose()
     
    return X_reduced

In [76]:
import pandas as pd
 
#Dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
data = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])


In [77]:
data

sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [78]:
 #Seleccionamos solo las caracteristicas
x = data.iloc[:,0:4]

In [79]:
x

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [80]:
target = data.iloc[:,4]

In [81]:
#Aplicamos la función de PCA
mat_reduced = PCA(x , 2)

In [83]:
data

sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [82]:
mat_reduced

array([[ 2.68420713,  0.32660731],
       [ 2.71539062, -0.16955685],
       [ 2.88981954, -0.13734561],
       [ 2.7464372 , -0.31112432],
       [ 2.72859298,  0.33392456],
       [ 2.27989736,  0.74778271],
       [ 2.82089068, -0.08210451],
       [ 2.62648199,  0.17040535],
       [ 2.88795857, -0.57079803],
       [ 2.67384469, -0.1066917 ],
       [ 2.50652679,  0.65193501],
       [ 2.61314272,  0.02152063],
       [ 2.78743398, -0.22774019],
       [ 3.22520045, -0.50327991],
       [ 2.64354322,  1.1861949 ],
       [ 2.38386932,  1.34475434],
       [ 2.6225262 ,  0.81808967],
       [ 2.64832273,  0.31913667],
       [ 2.19907796,  0.87924409],
       [ 2.58734619,  0.52047364],
       [ 2.3105317 ,  0.39786782],
       [ 2.54323491,  0.44003175],
       [ 3.21585769,  0.14161557],
       [ 2.30312854,  0.10552268],
       [ 2.35617109, -0.03120959],
       [ 2.50791723, -0.13905634],
       [ 2.469056  ,  0.13788731],
       [ 2.56239095,  0.37468456],
       [ 2.63982127,

In [84]:
principal_df = pd.DataFrame(mat_reduced , columns = ['PC1','PC2'])

In [85]:
#Añadimos la target a nuestras nuevas variables
principal_df = pd.concat([principal_df , pd.DataFrame(target)] , axis = 1)

In [86]:
data

sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [88]:
principal_df

PC1       PC2          target
0    2.684207  0.326607     Iris-setosa
1    2.715391 -0.169557     Iris-setosa
2    2.889820 -0.137346     Iris-setosa
3    2.746437 -0.311124     Iris-setosa
4    2.728593  0.333925     Iris-setosa
..        ...       ...             ...
145 -1.944017  0.187415  Iris-virginica
146 -1.525664 -0.375021  Iris-virginica
147 -1.764046  0.078519  Iris-virginica
148 -1.901629  0.115877  Iris-virginica
149 -1.389666 -0.282887  Iris-virginica

[150 rows x 3 columns]

## Sklearn

In [110]:
data

sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [111]:
from sklearn.decomposition import PCA
pca_= PCA(n_components=2)

In [112]:
pca_.fit(x)

PCA(n_components=2)

In [115]:
data_pca=pd.DataFrame(pca_.transform(x),columns=["PC1","PC2"])
data_pca["target"]=target

In [116]:
data_pca

PC1       PC2          target
0   -2.684207  0.326607     Iris-setosa
1   -2.715391 -0.169557     Iris-setosa
2   -2.889820 -0.137346     Iris-setosa
3   -2.746437 -0.311124     Iris-setosa
4   -2.728593  0.333925     Iris-setosa
..        ...       ...             ...
145  1.944017  0.187415  Iris-virginica
146  1.525664 -0.375021  Iris-virginica
147  1.764046  0.078519  Iris-virginica
148  1.901629  0.115877  Iris-virginica
149  1.389666 -0.282887  Iris-virginica

[150 rows x 3 columns]

In [117]:
data

sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
modelo
#modelo.train(data)
modelo.train(data_pca)

In [ ]:
5.9	3.0	5.1	1.8

23, 20

In [ ]:
modelo.predict([23,20])

iris-virginica

In [118]:
data_pca

PC1       PC2          target
0   -2.684207  0.326607     Iris-setosa
1   -2.715391 -0.169557     Iris-setosa
2   -2.889820 -0.137346     Iris-setosa
3   -2.746437 -0.311124     Iris-setosa
4   -2.728593  0.333925     Iris-setosa
..        ...       ...             ...
145  1.944017  0.187415  Iris-virginica
146  1.525664 -0.375021  Iris-virginica
147  1.764046  0.078519  Iris-virginica
148  1.901629  0.115877  Iris-virginica
149  1.389666 -0.282887  Iris-virginica

[150 rows x 3 columns]

In [119]:
data

sepal length  sepal width  petal length  petal width          target
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [105]:
#Porcentaje de varianza explicada por cada uno de los componentes seleccionados.
pca_.explained_variance_ratio_

array([0.92461621, 0.05301557, 0.01718514])

In [106]:
sum(pca_.explained_variance_ratio_[:-1])

0.9776317750248035

In [107]:
for n_compo in range(1,5):
    print(f"N componentes : {n_compo}")
    pca = PCA(n_components=n_compo)
    pca.fit(x)
    print(sum(pca.explained_variance_ratio_))
    print("\n")

N componentes : 1
0.9246162071742684


N componentes : 2
0.9776317750248035


N componentes : 3
0.9948169145498102


N componentes : 4
1.0000000000000002




In [108]:
df

NameError: name 'df' is not defined

## VARClus

- El algoritmo general es
- 1. Realiza PCA en el espacio de funciones actual. Si el valor propio máximo es menor que el umbral, detener la descomposición
- 2. Calcula los primeros componentes N PCA y asigna características a estos componentes según correlación absoluta de mayor a menor. Estos componentes son los centroides iniciales de estos grupos de variables.
- 3. Después de la asignación inicial, el algoritmo realiza una asignación iterativa denominada Más cercano Clasificación de componentes (NCS). Básicamente, los vectores centroides se vuelven a calcular como los primeros componentes de los grupos secundarios y el algoritmo reasignará cada una de las características basado en la misma regla de correlación.
- 4. Después de NCS, el algoritmo intenta aumentar la varianza total explicada por la primera
            Componente PCA de cada clúster secundario mediante la reasignación de funciones entre clústeres

In [103]:
from varclushi import VarClusHi

In [104]:
df=pd.read_excel("../datos/var_clustering.xlsx")

In [41]:
df.head()

Y   X1  X2       X3  X4  X5  X6  X7    X8  X9  ...  X54  X55  X56  X57  \
0  0  0.7   1  1986.81   0   1   1   0  0.00   0  ...    0    0    0    0   
1  0  0.5   1  1594.84   0   1   0   0  0.00   0  ...    0    0    0    0   
2  0  8.8   1  1437.57   0  12   1   0  0.00   0  ...    0    0    0    0   
3  0  0.8   1   190.03   0   1   0   1  5.65   0  ...    1    0    0    0   
4  0  3.0   1  1772.13   0   1   1   0  0.00   0  ...    0    0    0    0   

   X58  X59  X60  X61  X62  X63  
0    0    0    0    0    0    0  
1    0    0    0    0    1    0  
2    0    0    0    0    1    0  
3    0    0    0    1    0    0  
4    0    0    0    0    1    0  

[5 rows x 64 columns]

In [42]:
df.drop(columns=["Y"],inplace=True)

In [43]:
vc = VarClusHi(df,maxeigval2=.7)

In [44]:
vc.varclus()

In [45]:
vc.rsquare

Cluster Variable  RS_Own     RS_NC      RS_Ratio
0        0      X47     1.0  0.239117 -5.836501e-16
1        0      X48     1.0  0.239117 -5.836501e-16
2        0      X49     1.0  0.239117 -5.836501e-16
3        0      X50     1.0  0.239117 -5.836501e-16
4        0      X51     1.0  0.239117 -5.836501e-16
..     ...      ...     ...       ...           ...
58      35      X10     1.0  0.177260  0.000000e+00
59      36       X6     1.0  0.148685  0.000000e+00
60      37      X13     1.0  0.203811  0.000000e+00
61      38      X61     1.0  0.237247  0.000000e+00
62      39      X36     1.0  0.378398  0.000000e+00

[63 rows x 5 columns]

In [46]:
vc.rsquare[vc.rsquare["Cluster"]==4]

Cluster Variable    RS_Own     RS_NC  RS_Ratio
17       4      X34  0.841658  0.026168  0.162597
18       4      X37  0.841658  0.332347  0.237162

In [47]:
vc.rsquare.sort_values(["Cluster","RS_Ratio"],ascending=True).drop_duplicates(subset=["Cluster"],keep="first")

Cluster Variable    RS_Own     RS_NC      RS_Ratio
0        0      X47  1.000000  0.239117 -5.836501e-16
8        1      X55  0.993554  0.134418  7.447489e-03
13       2      X43  1.000000  0.093125  0.000000e+00
16       3      X25  0.914615  0.040861  8.902227e-02
17       4      X34  0.841658  0.026168  1.625967e-01
19       5      X23  0.996067  0.036627  4.082902e-03
21       6      X21  0.728479  0.030901  2.801794e-01
24       7      X16  0.919441  0.061120  8.580370e-02
26       8       X8  0.761587  0.032575  2.464410e-01
27       9      X17  0.717794  0.018556  2.875415e-01
29      10      X38  1.000000  0.197463  0.000000e+00
31      11      X32  0.685680  0.053444  3.320672e-01
32      12      X14  1.000000  0.064658  0.000000e+00
33      13      X62  0.738531  0.116891  2.960779e-01
35      14      X45  1.000000  0.021739  0.000000e+00
36      15      X42  0.799627  0.220752  2.571358e-01
39      16      X12  1.000000  0.060384  0.000000e+00
40      17      X40  1.000000  0.001597  0.000000e+00
41      18      X19  1.000000  0.105905  0.000000e+00
42      19      X39  1.000000  0.197463  0.000000e+00
43      20      X46  1.000000  0.006054  0.000000e+00
44      21      X20  1.000000  0.105905  0.000000e+00
45      22      X60  1.000000  0.019402  0.000000e+00
46      23      X29  1.000000  0.917929  0.000000e+00
47      24       X1  1.000000  0.020947  0.000000e+00
48      25       X4  1.000000  0.004393  0.000000e+00
49      26       X3  1.000000  0.109027  0.000000e+00
50      27      X33  1.000000  0.011671  0.000000e+00
51      28      X41  1.000000  0.093339  0.000000e+00
52      29      X11  1.000000  0.060384  0.000000e+00
53      30       X9  1.000000  0.078361  0.000000e+00
54      31      X31  1.000000  0.917929  0.000000e+00
55      32      X44  1.000000  0.047855  0.000000e+00
56      33      X28  1.000000  0.155108  0.000000e+00
57      34      X35  1.000000  0.378398  0.000000e+00
58      35      X10  1.000000  0.177260  0.000000e+00
59      36       X6  1.000000  0.148685  0.000000e+00
60      37      X13  1.000000  0.203811  0.000000e+00
61      38      X61  1.000000  0.237247  0.000000e+00
62      39      X36  1.000000  0.378398  0.000000e+00

In [48]:
columns=list(vc.rsquare.sort_values(["Cluster","RS_Ratio"],ascending=True).drop_duplicates(subset=["Cluster"],keep="first")["Variable"].values)

In [49]:
len(columns)

40

In [50]:
df[columns]

X47  X55      X43  X25  X34  X23  X21  X16    X8  X17  ...  X9  \
0        0    0   446.93    0    4    0    0  0.0  0.00    0  ...   0   
1        0    0  1144.24    0  125    0    0  0.0  0.00    0  ...   0   
2        0    0  2237.69    0   55    0    0  0.0  0.00    0  ...   0   
3        1    0   880.25    0   20    0    0  0.0  5.65    0  ...   0   
4        0    0  1143.44    0   25    0    0  0.0  0.00    0  ...   0   
...    ...  ...      ...  ...  ...  ...  ...  ...   ...  ...  ...  ..   
21507    0    0     0.00    0   53    0    0  0.0  0.00    0  ...   0   
21508    0    0     0.00    1   10    0    1  0.0  0.00    0  ...   0   
21509    0    0     0.00    0   69    0    0  0.0  0.00    0  ...   0   
21510    0    1  3226.87    0   34    0    0  0.0  0.00    0  ...   2   
21511    0    0     0.00    0   42    0    0  0.0  0.00    0  ...   0   

            X31  X44  X28  X35  X10  X6  X13  X61  X36  
0          0.00    0    0    1    0   1    1    0  7.0  
1         65.76    0    0    1    1   0    1    0  7.5  
2      85202.99    0    1    1    0   1    1    0  3.5  
3          0.00    0    0    0    0   0    1    1  4.0  
4          0.00    0    0    1    1   1    0    0  7.5  
...         ...  ...  ...  ...  ...  ..  ...  ...  ...  
21507      0.00    0    0    0    0   0    0    0  6.0  
21508   8791.40    0    0    0    0   0    0    0  4.0  
21509      0.00    0    0    1    0   0    0    0  6.5  
21510      0.00    0    0    1    0   1    1    0  6.5  
21511      0.00    0    0    0    0   0    0    0  7.5  

[21512 rows x 40 columns]